export { default as Navbar } from './navbar'
export { default as HomePage } from './Homepage'
export { default as Exchanges } from './Exchanges'
export { default as Crypto } from './Crypto'
export { default as CryptoDetails } from './CryptoDetails'
export { default as News } from './news'